version: '2'

services:

  postgres:
    build: ./postgres
    volumes:
      - "/opt/teamcity/pg_data:/var/lib/postgresql/data"
      - "/opt/teamcity/pg_backup:/backups"
    env_file: .env
    restart: always

  server:
    image: jetbrains/teamcity-server:latest
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  agent:
    image: jetbrains/teamcity-minimal-agent:latest
    env_file: .env
    restart: always
