version: '3'

services:
  server:
    image: jetbrains/teamcity-server:latest
    networks:
      - web
      - default
    volumes:
      - "/tmp/teamcity/data:/data/teamcity_server/datadir"
      - "/tmp/teamcity/logs:/opt/teamcity/logs"
    hostname: ${VIRTUAL_HOST}
    ports:
      - "8111"
    depends_on:
      - postgres
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
    # VIRTUAL_HOST for local case should be localhost
    # if you wanna nossl version for non local case... no, you don't
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.docker.network=web"
      - "traefik.port=8111"

  agent:
    build: ./agents/python-node-yarn
    env_file: .env
    depends_on:
      - redis
    #     if you need docker inside the agent
    #     (http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"

  postgres:
    build: ./postgres
    volumes:
      - "/tmp/teamcity/pg_data:/var/lib/postgresql/data"
      - "/tmp/teamcity/pg_backup:/backups"
    env_file: .env
    labels:
      - "traefik.enable=false"

  traefik:
    image: traefik
    restart: always
    command: --docker
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml

networks:
  web:
    external: true
